version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestNewP1Project
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestNewP1Project
  gitUsername: PoojaAnandGit
  gitBranch: main
